#!/bin/sh

echo ""
echo " __  __ _____ ____ ____  _____ _____   _   _ ____   ____ "
echo "|  \/  | ____/ ___|  _ \| ____|__  /  | | | |  _ \ / ___|"
echo "| |\/| |  _|| |  _| |_) |  _|   / /   | |_| | |_) | |    "
echo "| |  | | |__| |_| |  _ <| |___ / /_   |  _  |  __/| |___ "
echo "|_|  |_|_____\____|_| \_\_____/____|  |_| |_|_|    \____|"
echo ""

# 系统盘
system_disk_total=$(df -hP / | awk 'NR==2 {print $2}')
system_disk_used=$(df -hP / | awk 'NR==2 {print $3}')
system_disk_percent=$(df -hP / | awk 'NR==2 {print $5}')

# 数据盘
data_disk_total=$(df -hP /root/megrez-tmp | awk 'NR==2 {print $2}')
data_disk_used=$(df -hP /root/megrez-tmp | awk 'NR==2 {print $3}')
data_disk_percent=$(df -hP /root/megrez-tmp | awk 'NR==2 {print $5}')

if [ "$data_disk_used" = "0" ]; then
    data_disk_used="0M"
fi

echo "╔══════════════════╦══════════╦══════╦══════════════════╦═══════════════╦═══════════════════════════════════════════════════╗"
echo "║ 目录             ║ 名称     ║ 速度 ║ 已用 / 总量      ║ 使用率        ║ 说明                                              ║"
echo "╠══════════════════╬══════════╬══════╬══════════════════╬═══════════════╬═══════════════════════════════════════════════════╣"

printf "║ %-16s ║ 系 统 盘 ║  快  ║ %6s / %-7s ║ %11s   ║ 实例关机数据不会丢失，可存放代码等。              ║\n" \
    "/" \
    "$system_disk_used" \
    "$system_disk_total" \
    "$system_disk_percent"

printf "║ %-16s ║ 数 据 盘 ║  快  ║ %6s / %-7s ║ %11s   ║ 实例关机数据不会丢失，可存放读写IO要求高的数据。  ║\n" \
    "/root/megrez-tmp" \
    "$data_disk_used" \
    "$data_disk_total" \
    "$data_disk_percent"

printf "║ %-16s ║ 公 共 盘 ║  慢  ║ %-16s ║ %-13s ║ 删除实例数据不会丢失，但数据所有人都可以访问。    ║\n" \
    "/root/megrez-pub" \
    "" \
    ""

echo "╚══════════════════╩══════════╩══════╩══════════════════╩═══════════════╩═══════════════════════════════════════════════════╝"