{
 "title": "Node Detail",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))",
     "legendFormat": "平均使用率"
    },
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"idle\"}[1m])",
     "legendFormat": "CPU-{{cpu}}"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "可用" },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "总内存" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "已用"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "使用率"
    }
   ]
  },
  {
   "title": "GPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio",
     "legendFormat": "GPU-{{uuid}}"
    }
   ]
  },
  {
   "title": "显存信息",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nvidia_smi_memory_used_bytes", "legendFormat": "GPU-{{uuid}}-已用显存" },
    {
     "expr": "(nvidia_smi_memory_used_bytes / nvidia_smi_memory_total_bytes) * 100",
     "legendFormat": "GPU-{{uuid}}-使用率"
    }
   ]
  }
 ]
}