name: Build GPU-Managet Images
on:
  push:
    tags:
      - '*Ubuntu*'
  workflow_dispatch:

jobs:
  ubuntu-2204:
    name: Build Custom Image Ubuntu 22.04
    runs-on: docker-buildler
    if: gitea.event.ref == 'refs/tags/Ubuntu-22.04'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Proxy
        run: |
          mkdir -p /etc/systemd/system/docker.service.d
          echo -e "[Service]\nEnvironment=\"HTTP_PROXY=http://172.17.0.1:10809/\"\nEnvironment=\"HTTPS_PROXY=http://172.17.0.1:10809/\"" > /etc/systemd/system/docker.service.d/http-proxy.conf
          service docker restart 

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.Ubuntu-22.04
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gpu-manager:ubuntu-22.04

  pytorch_2_1_2_cuda_12_1_python_3_10_ubuntu_22_04:
    name: Build PyTorch 2.1.2 CUDA 12.1 Python 3.10 Ubuntu 22.04
    runs-on: docker-buildler
    if: gitea.event.ref == 'refs/tags/PyTorch-2.1.2-CUDA-12.1-Python-3.10-Ubuntu-22.04'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Proxy
        run: |
          mkdir -p /etc/systemd/system/docker.service.d
          echo -e "[Service]\nEnvironment=\"HTTP_PROXY=http://172.17.0.1:10809/\"\nEnvironment=\"HTTPS_PROXY=http://172.17.0.1:10809/\"" > /etc/systemd/system/docker.service.d/http-proxy.conf
          service docker restart 

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.Pytorch-2.1.2_Cuda-12.1_Python-3.10_Ubuntu-22.04
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gpu-manager:pytorch-2.1.2_cuda-12.1_python-3.10_ubuntu-22.04
  
  pytorch_2_3_1_cuda_12_1_python_3_11_ubuntu_22_04:
    name: Build PyTorch 2.3.1 CUDA 12.1 Python 3.11 Ubuntu 22.04
    runs-on: docker-buildler
    if: gitea.event.ref == 'refs/tags/PyTorch-2.3.1-CUDA-12.1-Python-3.11-Ubuntu-22.04'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set Proxy
        run: |
          mkdir -p /etc/systemd/system/docker.service.d
          echo -e "[Service]\nEnvironment=\"HTTP_PROXY=http://172.17.0.1:10809/\"\nEnvironment=\"HTTPS_PROXY=http://172.17.0.1:10809/\"" > /etc/systemd/system/docker.service.d/http-proxy.conf
          service docker restart 

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.Pytorch-2.3.1_Cuda-12.1_Python-3.11_Ubuntu-22.04
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gpu-manager:pytorch-2.3.1_cuda-12.1_python-3.11_ubuntu-22.04

  pytorch_2_4_0_cuda_12_1_python_3_12_ubuntu_22_04:
    name: Build PyTorch 2.4.0 CUDA 12.1 Python 3.12 Ubuntu 22.04
    runs-on: docker-buildler
    if: gitea.event.ref == 'refs/tags/PyTorch-2.4.0-CUDA-12.1-Python-3.12-Ubuntu-22.04'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Proxy
        run: |
          sh -c 'env | grep -i  _PROXY'
          mkdir -p /etc/systemd/system/docker.service.d
          echo -e "[Service]\nEnvironment=\"HTTP_PROXY=http://172.17.0.1:10809/\"\nEnvironment=\"HTTPS_PROXY=http://172.17.0.1:10809/\"" > /etc/systemd/system/docker.service.d/http-proxy.conf

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.Pytorch-2.4.0_Cuda-12.1_Python-3.12_Ubuntu-22.04
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gpu-manager:pytorch-2.4.0_cuda-12.1_python-3.12_ubuntu-22.04