name: Build GPU-Managet Images
on:
  push:
    tags:
      - '*ubuntu*'
  workflow_dispatch:

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: docker-buildler
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            env.http_proxy=172.17.0.1:10809
            env.https_proxy=172.17.0.1:10809
          config-inline: |
            [registry."docker.io"]
              mirrors = ["hub-docker.xiao-gy.tk"]

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.${{ gitea.ref_name }}
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gpu-manager:${{ gitea.ref_name }}
          build-args: |
            HTTP_PROXY=http://172.17.0.1:10809
            HTTPS_PROXY=http://172.17.0.1:10809
